import type { Metadata } from "next";
import {
  Bowlby_One,
  Caveat,
  Corinthia,
  Fira_Code,
  Inter,
  Michroma,
  Poppins,
} from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import localFont from "next/font/local";
import GoogleMapsProvider from "@/providers/GoogleMapsProvider";
import "../styles/globals.css";
import AppProviders from "@/providers/AppProviders";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const michroma = Michroma({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-michroma",
});

const corinthia = Corinthia({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-corinthia",
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-caveat",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-firacode",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const bowlbyOne = Bowlby_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bowlby-one",
});

const signatureFont = localFont({
  src: "../../public/fonts/signature_font.ttf",
  variable: "--font-signature",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    initMap: () => void;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} ${michroma.variable} ${signatureFont.variable} ${firaCode.variable} ${corinthia.variable} ${bowlbyOne.variable} ${caveat.variable}`}
      >
        <AppRouterCacheProvider>
          <AppProviders>
            <GoogleMapsProvider>{children}</GoogleMapsProvider>
          </AppProviders>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
